version: '3.8'

services:

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - "5432:5432"